Speech-Rule-Engine/speech-rule-engine

src/highlighter/html_highlighter.js

Ok, this time I patched the html highlighter.  Rather than handle maction as a special case, I just insert the correct bounding box for all elements.  It doesn't hurt to do it for maction as well.
I removed the separate function for setting relative position, since it is not really needed with this code any longer.
I also save the `position` status and return the element to the original style setting when it is unhighlighted.

Create properly-sized bounding box for arbitrary HTML-CSS elements

---

src/highlighter/svg_highlighter.js

This pull provides a work-around for the WebKit bug that is causing the problems with highlighting fences in issue #29.  The problem is that `getBBox()` doesn't take the `x` attribute into account, so you get the wrong placement of the highlight rectangle.  The work-around is to temporarily wrap the `<use>` element in a `<g>` and use `getBBox()` on that.  Ugly, but it seems to work for me.

Work around WebKit bug with getBBox() on <use> elements.

---

src/semantic_tree/semantic_attr.js
src/semantic_tree/semantic_tree.js
tests/enrich_mathml_test.js

Treatment of some underover cases similar to subsup.
Avoids redundant information in the type/role slots.

Underover case

---

src/common/externs.js
src/semantic_tree/semantic_tree.js
src/semantic_tree/semantic_util.js
src/walker/abstract_walker.js
tests/enrich_mathml_test.js
tests/mathspeak_embellish_test.js
tests/semantic_tree_test.js

categories. Thereby fixes the error if a semantic element has a singleton child
and an annotation.

Adds semantic and annotation elements into the correct MathML element

---

doc/diagram-project.org
src/walker/abstract_walker.js
src/walker/focus.js
src/walker/semantic_walker.js
src/walker/syntax_walker.js
src/walker/walker_util.js

Solves the general problem of MathJax omitting intermediate elements (as described in the SVG case in #21) by  basing walking on re-constructed semantic tree rather than the DOM nodes only. DOM nodes for highlighting are computed as much as possible from existing DOM nodes and semantic tree information.

Refactor focus

---

src/enrich_mathml/case_binomial.js
src/enrich_mathml/case_multiline.js
src/enrich_mathml/case_table.js
src/enrich_mathml/enrich_cases.js
src/semantic_tree/semantic_mathml.js
src/semantic_tree/semantic_pred.js
src/semantic_tree/semantic_processor.js
src/walker/abstract_walker.js
src/walker/focus.js
src/walker/rebuild_stree.js
tests/enrich_mathml_test.js
tests/rebuild_stree_test.js
tests/semantic_tree_test.js
tmp/branches
tmp/issues.js

Handles all walking issues related to [a11y 161](https://github.com/mathjax/MathJax-a11y/issues/161)
Still some UX discrepancy for 
* binomial from fraction vs from table
* binomial from fraction if padding elements (mrow, mpadded etc.) are available of not
* prefix announcements for elements in cases/multilines.

Restore collapse handling

---

doc/moss-project.org
src/common/auditory_description.js
src/rule_engine/dynamic_cstr.js
src/rule_engine/grammar.js
src/rule_engine/math_simple_store.js
src/rule_engine/math_store.js
src/rule_engine/speech_rule.js
src/rule_engine/speech_rule_engine.js
src/speech_rules/mathml_store_rules.js
src/speech_rules/mathml_store_util.js
src/speech_rules/mathspeak_rules.js
src/speech_rules/mathspeak_util.js
src/speech_rules/semantic_tree_rules.js
tests/api_test.js
tests/mathml_cloud_test.js

New data structure to keep grammatical information and pass it on during the rule dispatch.
Gets rid of some of the hacks introduced for determinants, font handling, etc. 
Still to do: Get rid of the explicit preprocess flag. This could be avoided if we were to process and finalise all auditory descriptions immediately. That is a left-over artefact of ChromeVox and the symbol mappings running in the background page.

Grammatic structure

---

src/indexing/trie_node_factory.js
src/rule_engine/grammar.js
src/rule_engine/speech_rule.js
src/rule_engine/speech_rule_engine.js
tests/speech_rule_test.js

Refactors speech rules to explicitly handle attributes and grammar annotations.

Refactor rule attributes

---

src/speech_rules/abstraction_rules.js

Forces reordering of superscript rules to promote abstractions.

Fixes MathJax A11Y issue #176.

---

resources/doc/notes.org
src/indexing/trie.js
src/indexing/trie_node_factory.js
src/rule_engine/base_rule_store.js
src/rule_engine/speech_rule.js
src/rule_engine/speech_rule_context.js
src/rule_engine/speech_rule_engine.js
src/speech_rules/clearspeak_french.js
src/speech_rules/clearspeak_rules.js
src/speech_rules/mathspeak_french.js
src/speech_rules/mathspeak_spanish.js
tests/clearspeak_french_rule_test.js
tests/clearspeak_rule_test.js
tests/mathml_rule_test.js
tests/mathspeak_embellish_french_test.js
tests/mathspeak_embellish_spanish_test.js
tests/mathspeak_embellish_test.js
tests/mathspeak_english_test.js
tests/mathspeak_french_test.js
tests/mathspeak_spanish_test.js
tests/mmlcloud_english_test.js
tests/mmlcloud_french_test.js
tests/mmlcloud_spanish_test.js
tests/noble_english_test.js
tests/noble_french_test.js
tests/noble_spanish_test.js
tests/semantic_rule_test.js

* Introduces function contexts for single speech rules.
* Cleaner separation of custom functions in rules.
* Removes interactions between different rule sets via named custom functions
* Removes rule set restrictions in speech rule tests.

Separate constraint functions

---

src/common/variables.js

Updates the path to always load the latest version of `wicked-good-xpath` from `jsdelivr`.
_Note, this is based on the `wicked-good-xpath` npm package and __NOT__ on the `wgxpath` package._

Updates wgxpath path for Edge/IE

---

Makefile

Replaces the use of `head -n -1` by `sed '$d'` in the Makefile for compatibility with non-GNU implementations of `head` (e.g., Mac OSX).
Solves issue #348 .

Changes makefile to avoid negative head parameter.

---

src/common/cli.js
src/semantic_tree/semantic_skeleton.js

* Fixes missing top-level `owns` attribute.
* Fixes incorrect call for CLI option `structure`.
Completes #318

Owns issue

---

src/semantic_tree/semantic_processor.js
tests/base/enrich_mathml_test.js
tests/base/semantic_tree_test.js

Rewrites interpretation of integral variable as prefix operator rather than (invisible) comma separated list.
Inspired by issue #394 .

Improved Integral variable treatment

---

src/semantic_tree/semantic_skeleton.js

Computes the `owns` attribute for existing syntactic nodes only.
Solves issue #418.

Correct owns attributes

---

src/audio/auditory_description.js

Personality annotations not correctly cloned, which lead to problems when inserting deep speech with markup.

Corrects cloning of auditory descriptions.

---

Makefile
src/common/system.js
src/mathmaps/en/rules/chromevox.js
src/rule_engine/speech_rule_engine.js
src/speech_rules/other_rules.js

* Maps default domain to be MathSpeak
* Renames the `default` set to `chromevox`
Fixes two major problems:
* In locale `en`: Forgetting to specify a rule set leads to the original ChromeVox rules being used, which are very ambiguous without full prosody.
* If selecting a locale other than `en` without explicitly specifying a rule set, the output would be garbage.

Maps default domain to mathspeak.

---

src/enrich_mathml/enrich_mathml.js
src/semantic_tree/semantic_heuristics.js
src/semantic_tree/semantic_processor.js
src/walker/rebuild_stree.js

This fixes odds and ends stemming from releasing the new juxtaposition heuristics into the wild. 
* Correct issue of implicit operations becoming operators themselves.
* Optimises ordering of invisible times.
* Systematic treatment of multiple invisible times similar to regular pre/post fix operations.
* Ensures correct ordering for enrichment, while retaining sub positions in tree elements
Along the way it fixes some longstanding issues and general problems:
* Solution for destructive dropping of explicit function applications. 
* Ensures that only func apps that are newly introduced will be marked as added.
* Robust rebuilding of semantic tree, regardless of tree order of mml nodes.
* Fixes nearly all cases where enrichment might lead to orphaned child nodes. There is still a minor …

Enrich juxta heuristic

---

src/walker/abstract_walker.js

Adds refocus method to the walkers in case the node structure has been altered outside the control of the walker, e.g., by collapsing a node via mouse click.
This solves the issue mentioned in [Mathjax PR 683](https://github.com/mathjax/MathJax-src/pull/683)

Adds a refocus method for walkers.

---

src/mathmaps/en/rules/clearspeak_english.js
src/speech_rules/clearspeak_preferences.js

Adds new Clearspeak rules for enclosed elements including a specialised preference.  Solve issue #435 and related issue #361

Adds enclose rules to en.

---

ts/semantic_tree/semantic_pred.ts
ts/semantic_tree/semantic_processor.ts

Avoids rewriting a table to matrix or vector when the table structure is introduced due to equation labelling.

Solves issue #616.

---

README.md
ts/common/cli.ts
ts/common/engine.ts
ts/common/engine_setup.ts
ts/common/system.ts
ts/common/variables.ts
ts/l10n/l10n.ts
ts/rule_engine/dynamic_cstr.ts
ts/speech_rules/clearspeak_rules.ts
ts/speech_rules/math_map.ts
ts/speech_rules/mathspeak_rules.ts
ts/speech_rules/other_rules.ts
ts/speech_rules/speech_rules.ts

Ensures cleaner handling of locale loading on SRE startup. In particular, this PR 
* removes the `delay` flag.
* sequences promises for loading of `base`, `default` and selected locale
* ensure `engineReady` waits for all locales to be loaded
* adds customisation for `defaultLocale`
* correct inheritance of function stores from a base store, rather than English. This failed, when English is **not** the default.

Startup Improvements

---

mathmaps/base/rules/clearspeak_base.json
mathmaps/base/rules/mathspeak_base.json
ts/enrich_mathml/enrich_mathml.ts

Fixes `mfenced` issue with unusual fences/separators, etc. Originally reported via MathJax (@dpvc )

Mfenced issue

---

ts/speech_rules/clearspeak_preferences.ts

This can now be fully done in MathJax.

Removes clearspeak preference menu computations.

---

ts/speech_rules/math_map.ts

Fixes error when XHR has wrapper and returns proper js object instead of the string.

Fixes error when XHR has wrapper and returns proper js object instead the string.

---

mathmaps/euro/rules/euro.json
mathmaps/nemeth/rules/nemeth.json
ts/speech_rules/nemeth_util.ts

Mostly fixes issue #665 .
The only exception are numbers in nemeth Braille, which do not get the correct prefix number symbol.

adds some literal Braille translation for alt texts
