- src/common/browser_util.js
- src/common/system_external.js
Uses location protocol for json loading.
> Adapt protocol

- src/common/system_external.js
Fixes https://github.com/mathjax/MathJax-RespEq/issues/51
> Adds protocol for URL in constant.

- .npmignore
- .travis.yml
- README.md
- package.json
- src/common/api.js
- src/common/auditory_description.js
- src/common/cli.js
- src/common/externs.js
- src/common/system.js
- src/common/system_external.js
- tests/abstract_rule_test.js
Merge into new develop branch.
> Api semantic

- src/walker/semantic_walker.js
> Fixes missing base case for punctuations.

- src/walker/abstract_walker.js
- src/walker/walker_util.js
Factoring out utility functions from class methods for walkers.
> Refactor walker utilities

- src/common/browser.js
- src/common/externs.js
- src/common/system.js
- src/common/system_external.js
- src/enrich_mathml/enrich_mathml.js
- src/mathmaps/math_map.js
- src/semantic_tree/semantic_tree.js
- src/walker/rebuild_stree.js
Enables local configuration from webpages.
Also does some refactoring to reduce code duplication.
> External configs

- src/common/engine.js
- src/common/system.js
- src/enrich_mathml/enrich_mathml.js
- src/rule_engine/base_rule_store.js
- src/rule_engine/speech_rule_engine.js
- src/semantic_tree/semantic_tree.js
- src/speech_rules/combined_store.js
- src/speech_rules/mathspeak_util.js
- src/speech_rules/prefix_rules.js
- src/walker/abstract_speech_generator.js
- src/walker/abstract_walker.js
- src/walker/adhoc_speech_generator.js
- src/walker/dummy_walker.js
- src/walker/levels.js
- src/walker/node_speech_generator.js
- src/walker/rebuild_stree.js
- src/walker/semantic_walker.js
- src/walker/syntax_walker.js
- src/walker/tree_speech_generator.js
- src/walker/walker_interface.js
- src/walker/walker_util.js
- tests/externs.js
- tests/prefix_rule_test.js
- tests/tests.js
Adds the following features/improvements:
- Prefix computation for positional announcments
- Depth for level announcement
- Move tracking
- Repetition of current element
- Strict feature for the speech rule engine
> Add prefixes

- src/common/browser_util.js
- src/common/dom_util.js
- src/common/engine.js
- src/common/mathjax.js
- src/common/system.js
- src/enrich_mathml/enrich_mathml.js
- src/highlighter/abstract_highlighter.js
- src/highlighter/svg_highlighter.js
- src/mathmaps/math_map.js
- src/semantic_tree/semantic_tree.js
- src/speech_rules/abstraction_rules.js
- src/speech_rules/combined_store.js
- src/speech_rules/prefix_rules.js
- src/speech_rules/semantic_tree_rules.js
- src/walker/abstract_speech_generator.js
- src/walker/abstract_walker.js
- src/walker/direct_speech_generator.js
- src/walker/dummy_speech_generator.js
- src/walker/dummy_walker.js
- src/walker/focus.js
- src/walker/levels.js
- src/walker/node_speech_generator.js
- src/walker/rebuild_stree.js
- src/walker/semantic_walker.js
- src/walker/speech_generator_interface.js
- src/walker/syntax_walker.js
- src/walker/tree_speech_generator.js
- tests/prefix_rule_test.js
Adds full handling of maction and integrates abstraction rules.
> Add abstractions

- src/common/mathjax.js
- src/enrich_mathml/enrich_mathml.js
- src/walker/summary_speech_generator.js
- Adds summary generator for most collapsed expression.
- Fixes a problem with maction connection that occurred when expression was walked before speech generation was switched on.
> Add summary generator

- Makefile
- src/common/auditory_description.js
- src/common/dom_util.js
- src/common/engine.js
- src/common/system.js
- src/enrich_mathml/case_embellished.js
- src/mathmaps/math_map.js
- src/rule_engine/base_rule_store.js
- src/rule_engine/dynamic_cstr.js
- src/rule_engine/math_simple_store.js
- src/rule_engine/math_store.js
- src/rule_engine/speech_rule.js
- src/rule_engine/speech_rule_engine.js
- src/rule_engine/speech_rule_store.js
- tests/mathml_store_test.js
- tests/tests.js
CL implements most of T1.1 of MOSS project.
CL also resolves dependencies, so SRE can again be compiled in full strict mode under new closure-library.
We therefore merge into develop and only afterwards forkin separate moss and diagram branches.
> Refactor constraints

- src/common/auditory_description.js
- src/rule_engine/speech_rule_engine.js
- src/speech_rules/prefix_rules.js
- tests/prefix_rule_test.js
Fixes caching to avoid interference with contexts.
Adds prefix handling for tabular structures.
> Adjust context caching

- doc/diagram-project.org
- src/enrich_mathml/case_line.js
- src/enrich_mathml/enrich_mathml.js
- src/semantic_tree/semantic_attr.js
- src/semantic_tree/semantic_mathml.js
- src/semantic_tree/semantic_pred.js
- src/semantic_tree/semantic_processor.js
- src/speech_rules/mathspeak_rules.js
- src/walker/abstract_walker.js
- src/walker/table_walker.js
- src/walker/walker.js
- src/walker/walker_factory.js
> Table walker

- doc/moss-project.org
- src/common/cli.js
- src/common/engine.js
- src/common/system.js
- src/rule_engine/base_rule_store.js
- src/rule_engine/dynamic_cstr.js
- src/rule_engine/math_simple_store.js
- src/rule_engine/math_store.js
- src/rule_engine/speech_rule_engine.js
Extended constraint system with flexible, customisable ordering and multiple choices per axis.
> Constraint system

- Makefile
- package.json
- src/audio/acss_renderer.js
- src/highlighter/abstract_highlighter.js
- src/highlighter/color_picker.js
- src/highlighter/highlighter.js
- src/highlighter/highlighter_factory.js
- src/indexing/abstract_trie_node.js
- src/rule_engine/dynamic_cstr.js
- src/rule_engine/grammar.js
- src/rule_engine/math_simple_store.js
- src/rule_engine/speech_rule.js
- src/rule_engine/speech_rule_engine.js
- src/rule_engine/speech_rule_functions.js
- src/semantic_tree/semantic_attr.js
- src/semantic_tree/semantic_processor.js
- src/semantic_tree/semantic_util.js
- src/speech_generator/speech_generator_factory.js
- src/speech_rules/mathspeak_util.js
- src/speech_rules/speech_rule_stores.js
- src/walker/focus.js
- src/walker/rebuild_stree.js
- src/walker/walker_factory.js
* Allow to use new closure version.
* Adapts Makefile to exclude closure NTI algorithm, which is default since Jan 2017.
* Removes some redundant type information in Object types.
> New closure version

- README.md
- src/common/api.js
- src/common/cli.js
- src/common/engine.js
Cleans up the API by
* removing deprecated functions
* duplicate functionality
* flipping the semantic flag
* updating the README
> Cleanup API

- README.md
- package.json
- src/audio/auditory_description.js
- src/common/externs.js
- src/common/system.js
- src/common/system_external.js
- src/enrich_mathml/enrich_mathml.js
- src/rule_engine/speech_rule_engine.js
- src/semantic_tree/semantic_mathml.js
- src/speech_rules/mathspeak_rules.js
- tests/enrich_mathml_test.js
- tests/mathml_cloud_test.js
- tests/rebuild_stree_test.js
> V2 bug fixes

- .gitignore
- src/common/cli.js
- src/common/engine.js
> Adds node_modules to gitignore.

- src/speech_rules/abstraction_rules.js
- src/speech_rules/abstraction_spanish.js
> Solves issue #213 for abstraction of nested roots.

- resources/www/localisation/SemanticTreeRules.html
- src/speech_rules/semantic_tree_rules.js
- tests/semantic_rule_test.js
Solves MathJax a11y [issue 225](https://github.com/mathjax/MathJax-a11y/issues/225).
> Adds a rule for mixed numbers to default (ChromeVox) rule set.

- src/semantic_tree/semantic_node.js
- tests/markup_test.js
Adds again the code to handle external attributes during enrichment.
> Regain lost code

- src/highlighter/abstract_highlighter.js
- src/highlighter/highlighter_factory.js
- src/highlighter/svg_highlighter.js
- src/highlighter/svg_v3_highlighter.js
- src/l10n/locale_nemeth.js
- src/speech_generator/speech_generator_util.js
- src/walker/abstract_walker.js
- src/walker/walker.js
Improvements for V3 to generate and run multiple highlighter. In general one highlighter per walker.
> V3 multi highlighters

- src/audio/ssml_renderer.js
- tests/base/markup_test.js
Puts floor function at the right place.
> Fixes issue #326.

- src/speech_rules/math_map.js
* Loads locale files on _need only_ basis
> Lazy locale loading

- src/common/cli.js
- src/l10n/l10n.js
Maps to English by default, case locale is unknown.
> Load English locale when given unknown locale on cli.

- README.md
Changes http to https (and updates jsdoc URL)
> docs(README.md): update various URLs

- src/mathmaps/en/units/currency.js
- src/semantic_tree/semantic_default.js
- src/semantic_tree/semantic_tree.js
- src/speech_rules/clearspeak_preferences.js
- src/speech_rules/clearspeak_rules.js
- src/speech_rules/clearspeak_util.js
- src/speech_rules/mathspeak_rules.js
- tests/base/enrich_mathml_test.js
> Clearspeak units

- src/l10n/locale_es.js
- src/l10n/messages.js
- src/mathmaps/en/units/currency.js
- src/rule_engine/grammar.js
- src/speech_rules/mathspeak_rules.js
- src/speech_rules/mathspeak_spanish.js
- src/speech_rules/mathspeak_spanish_util.js
- src/speech_rules/unit_util.js
Refactors some of the Spanish unit treatment to be available everywhere.
> Unit rewrite

- src/semantic_tree/semantic_processor.js
- src/semantic_tree/semantic_tree.js
> Unit cleanup

- src/semantic_tree/semantic_processor.js
- tests/base/enrich_mathml_test.js
Fixes division problem in issue #328
> Improve division

- src/semantic_tree/semantic_pred.js
- src/semantic_tree/semantic_processor.js
- tests/base/enrich_mathml_test.js
- tests/base/rebuild_stree_test.js
- tests/base/semantic_tree_test.js
> Improves singleton set heuristic. Solves Issue #287.

- src/highlighter/svg_v3_highlighter.js
Solves issue #409 and thereby https://github.com/mathjax/MathJax/issues/2529
> Solves highlighter problem issue #409.

- README.md
> fix(readme): simplify commander change warning

- Makefile
Fixes the `sed` issue in `Makefile`.
> Solves issue #434.

- src/mathmaps/de/rules/summary_german.js
- src/mathmaps/es/rules/summary_spanish.js
- src/mathmaps/fr/rules/summary_french.js
- src/mathmaps/it/rules/summary_italian.js
> Cleanup summary rules

- Makefile
- src/common/cli.js
- src/semantic_tree/semantic_heuristics.js
- src/semantic_tree/semantic_processor.js
- src/semantic_tree/semantic_util.js
Improves on the juxtaposition heuristic. Solves among other things issue #475
> Juxtaposition issue

- src/enrich_mathml/case_limit.js
- src/enrich_mathml/case_table.js
- src/enrich_mathml/case_text.js
- src/enrich_mathml/enrich_mathml.js
> Fixes issue #486.

- src/enrich_mathml/case_limit.js
> Avoid duplicating walk in truncated limit node.

- src/enrich_mathml/case_embellished.js
- src/enrich_mathml/enrich_mathml.js
> Correct insertion of empty fenced element.

- src/semantic_tree/semantic_mathml.js
> Keeps track of pseudo-empty elements.

- src/enrich_mathml/case_embellished.js
> Prevents revisiting embellished punctuation nodes twice.

- src/speech_generator/speech_generator_util.js
- src/speech_generator/tree_speech_generator.js
This solves [MathJax issue 555](https://github.com/mathjax/MathJax-src/issues/555)
> Solves incorrect speech for collapsed elements.

- src/mathmaps/de/rules/clearspeak_german.js
- src/mathmaps/de/rules/mathspeak_german.js
- src/mathmaps/en/rules/clearspeak_english.js
- src/mathmaps/en/rules/mathspeak_english.js
- src/mathmaps/es/rules/mathspeak_spanish.js
- src/mathmaps/fr/rules/clearspeak_french.js
- src/mathmaps/fr/rules/mathspeak_french.js
- src/mathmaps/it/rules/clearspeak_italian.js
- src/mathmaps/it/rules/mathspeak_italian.js
- src/mathmaps/nemeth/rules/nemeth_rules.js
- src/speech_rules/mathspeak_util.js
Better unicode handling to ensure that spreading out of upper plane characters is correct.
> Changes number rules to work better with spread out content.

- src/enrich_mathml/enrich_mathml.js
> Adds postfix computation for glyphs.

- src/mathmaps/de/rules/clearspeak_german.js
- src/mathmaps/de/rules/mathspeak_german.js
- src/mathmaps/en/rules/clearspeak_english.js
- src/mathmaps/en/rules/mathspeak_english.js
- src/mathmaps/es/rules/mathspeak_spanish.js
- src/mathmaps/fr/rules/clearspeak_french.js
- src/mathmaps/fr/rules/mathspeak_french.js
- src/mathmaps/it/rules/clearspeak_italian.js
- src/mathmaps/it/rules/mathspeak_italian.js
Issue #7 was effectively already solved. This just makes sure the speech now also works as expected.
> Fixes the last neutral fence sign.

- src/rule_engine/speech_rule_engine.js
- src/speech_rules/clearspeak_preferences.js
Code corrections that need to be ported to Typescript:
* Smart preference computation
* Firefox bug fix: Computing evaluator per XML document
> Corrections

- mathmaps/de/rules/clearspeak_german.js
- mathmaps/de/rules/summary_german.js
- mathmaps/en/rules/clearspeak_english.js
- mathmaps/en/rules/summary_english.js
- mathmaps/es/rules/summary_spanish.js
- mathmaps/fr/rules/clearspeak_french.js
- mathmaps/fr/rules/summary_french.js
- mathmaps/hi/rules/clearspeak_hindi.js
- mathmaps/hi/rules/summary_hindi.js
- mathmaps/hi/symbols/digits_rest.js
- mathmaps/it/rules/clearspeak_italian.js
- mathmaps/it/rules/summary_italian.js
- ts/common/cli.ts
- ts/indexing/trie.ts
- ts/rule_engine/base_rule_store.ts
- ts/rule_engine/math_simple_store.ts
- ts/rule_engine/math_store.ts
- ts/rule_engine/speech_rule.ts
- ts/rule_engine/speech_rule_engine.ts
- ts/rule_engine/speech_rule_store.ts
- ts/semantic_tree/semantic_util.ts
- ts/speech_rules/clearspeak_preferences.ts
Complete rewrite of unicode rule definition, storage and handling for faster lookup and smaller memory footprint.
> Rewrite unicode rules

- mathmaps/base/rules/clearspeak_base.json
- mathmaps/base/rules/mathspeak_base.json
- mathmaps/base/rules/prefix_base.json
- mathmaps/en/rules/chromevox.json
- mathmaps/en/rules/clearspeak_english_actions.json
- mathmaps/en/rules/emacspeak.json
- mathmaps/en/rules/mathspeak_english_actions.json
- mathmaps/en/symbols/math_symbols.json
- mathmaps/nemeth/rules/nemeth.json
- mathmaps/nemeth/rules/nemeth_actions.json
- mathmaps/nemeth/symbols/math_symbols.json
- ts/index.ts
- ts/rule_engine/base_rule_store.ts
- ts/rule_engine/speech_rule_engine.ts
- ts/semantic_tree/semantic_attr.ts
- ts/semantic_tree/semantic_pred.ts
- ts/semantic_tree/semantic_processor.ts
- ts/speech_rules/clearspeak_preferences.ts
Integrates new metric heuristic:
* New semantic role `metric` is used to distinguish neutral fences.
* Speech Rules for mathspeak and clearspeak are introduced.
* Rules adapted for new rule syntax.
* Currently English only!
> Metric heuristic

- mathmaps/base/rules/clearspeak_base.json
- mathmaps/base/rules/mathspeak_base_actions.json
- mathmaps/base/rules/mathspeak_base_romance.json
- mathmaps/de/rules/clearspeak_german_actions.json
- mathmaps/de/rules/mathspeak_german.json
- mathmaps/de/rules/mathspeak_german_actions.json
- mathmaps/en/rules/clearspeak_english_actions.json
- mathmaps/en/rules/mathspeak_english_actions.json
- mathmaps/es/rules/mathspeak_spanish.json
- mathmaps/es/rules/mathspeak_spanish_actions.json
- mathmaps/fr/rules/clearspeak_french_actions.json
- mathmaps/fr/rules/mathspeak_french.json
- mathmaps/fr/rules/mathspeak_french_actions.json
- mathmaps/hi/rules/clearspeak_hindi.json
- mathmaps/hi/rules/clearspeak_hindi_actions.json
- mathmaps/hi/rules/mathspeak_hindi.json
- mathmaps/hi/rules/mathspeak_hindi_actions.json
- mathmaps/it/messages/messages.json
- mathmaps/it/rules/clearspeak_italian_actions.json
- mathmaps/it/rules/mathspeak_italian.json
- mathmaps/it/rules/mathspeak_italian_actions.json
- ts/rule_engine/base_rule_store.ts
- ts/rule_engine/speech_rule_engine.ts
- ts/speech_rules/mathspeak_util.ts
Minimises the part of mathspeak rule sets that need to be localised.
> Reduce mathspeak

- ts/speech_rules/nemeth_util.ts
Corrects the mistakes introduced by PR #548
> Reverses changes of PR #548.

- mathmaps/en/units/speed.json
- mathmaps/nemeth/messages/messages.json
- mathmaps/nemeth/rules/nemeth.json
- mathmaps/nemeth/symbols/hebrew_letters.json
- ts/semantic_tree/semantic_attr.ts
Some fixes and issues mainly introduced by the recent conversions.
> Message move fixes

- ts/enrich_mathml/case_embellished.ts
- ts/semantic_tree/semantic_heuristics.ts
> Integrates cycle heuristic into regular speech generation.

- mathmaps/base/rules/clearspeak_base.json
- mathmaps/de/rules/clearspeak_german_actions.json
- mathmaps/en/rules/clearspeak_english_actions.json
- mathmaps/fr/rules/clearspeak_french_actions.json
- mathmaps/hi/rules/clearspeak_hindi_actions.json
- mathmaps/it/rules/clearspeak_italian_actions.json
- mathmaps/nb/rules/clearspeak_bokmal_actions.json
- mathmaps/nn/rules/clearspeak_nynorsk_actions.json
- mathmaps/sv/rules/clearspeak_swedish_actions.json
Corrects problems with integrals in clearspeak that had non-trivial variables.
> Clearspeak integral

- ts/common/engine.ts
- ts/common/engine_setup.ts
- ts/common/system.ts
- ts/speech_rules/math_map.ts
- webpack.config.js
* Delay feature for locale loading
* Exports the standard locale loader
> Mj integration

- ts/enrich_mathml/enrich_mathml.ts
- ts/semantic_tree/semantic_heuristic_factory.ts
- ts/semantic_tree/semantic_heuristics.ts
- ts/semantic_tree/semantic_processor.ts
Reverts Speech-Rule-Engine/speech-rule-engine#659
> Revert "Fix implicit regression"

- ts/semantic_tree/semantic_pred.ts
Solves https://github.com/mathjax/MathJax/issues/2979 Strengthens guard for elided multiplication.
> MJ issue 2979 

- ts/common/cli.ts
- ts/common/engine.ts
- ts/semantic_tree/semantic_skeleton.ts
Allows to switch on aria attribute selection as discussed in #690
> Hides aria attributes behind a flag.

- package-lock.json
- package.json
- ts/common/system_external.ts
Moves to latest version of @xmldom/xmldom
> New xmldom

- ts/enrich_mathml/enrich_mathml.ts
- ts/semantic_tree/semantic_heuristics.ts
- ts/semantic_tree/semantic_skeleton.ts
- ts/walker/semantic_walker.ts
- ts/walker/syntax_walker.ts
> Fixes issue #733. Refactors combinechildrencontent interface.

- ts/speech_generator/abstract_speech_generator.ts
- ts/speech_generator/speech_generator.ts
- ts/speech_generator/summary_speech_generator.ts
Speech functionality for new explorer version.
> Adds depth and actionable computations to speech generator.

- ts/semantic_tree/semantic_util.ts
Fixes enrichment issue reported by @dpvc on 11/11/2024.
> Bugfix: html elements in token

- ts/semantic_tree/semantic_heuristics.ts
- ts/semantic_tree/semantic_processor.ts
> implements a continental interval heuristic

- ts/enrich_mathml/enrich_mathml.ts
> fix to avoid duplicate semantic content with juxtaposition heuristic

- ts/semantic_tree/semantic_heuristic.ts
- ts/semantic_tree/semantic_heuristics.ts
- ts/semantic_tree/semantic_mathml.ts
Simple heuristic to collate identifier series into functional expression, if they exist.
This should improve cases like issue #767
> new heuristic to combine identifiers to known functions

- mathmaps/base/rules/mathspeak_base.json
- mathmaps/base/rules/mathspeak_base_actions.json
> Solves issue #728
